### ISSUE TITLE
AzureML Compute Job failed

### ISSUE THREAD

**Issue by priyanshi09** [microsoft/MCW-ML-Ops#62] opened 2022-02-15 17:25 UTC
Hi, 
Implementing the repository in my Devops environment and it fails on AzureML compute Job with error:  Failed to parse Job Spec due to invalid base64 encoding with error Encoded text cannot have a 6-bit remainder.",

Here is the log file, any ideas to fix this issue
[10.txt](https://github.com/microsoft/MCW-ML-Ops/files/8073218/10.txt)
?

**Comment by shirolkar** [comment] 2022-02-19 20:15
@priyanshi09 @timahenning @DawnmarieDesJardins I looked into this issue and I am not able to reproduce it. Priya can you confirm that you created new AML WS as per https://github.com/microsoft/MCW-ML-Ops/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20MLOps.md#task-3-create-an-azure-machine-learning-workspace with the **Container registry** specified? Thanks Jitendra

**Comment by DawnmarieDesJardins** [comment] 2022-02-24 22:39
Closing this issue as no further communication received.  Please reopen if needed.

**Closed by DawnmarieDesJardins** 2022-02-24 22:39 UTC
